application: 'smapptester'
runtime: java7
version: '2'
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
api_version: '1.0'
handlers:
- url: (/.*\.cache\..*\.nocache\..*/)
  static_files: __static__\1Audio.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/)
  static_files: __static__\1Audio.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*\.nocache\..*\.cache\..*/)
  static_files: __static__\1Audio.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*\.cache\..*/)
  static_files: __static__\1Audio.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 365d
- url: (/.*\.cache\..*\.nocache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*\.nocache\..*\.cache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*\.cache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 365d
- url: (/.*\.nocache\..*/)
  static_files: __static__\1Audio.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*/)
  static_files: __static__\1Audio.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*\.nocache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /.*
  script: unused
  login: optional
  secure: optional
- url: /_ah/spi/.*
  script: unused
  login: optional
  secure: optional
